defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: rstatus-development

test:
  <<: *defaults
  database: rstatus-test

production:
  <<: *defaults
  database: rstatus-prod
  username: rstatus
  password: eiTh3aeJ{aeTha
